### ISSUE TITLE
Mensagem de erro ao salvar ocorrência. 

### ISSUE THREAD

**Issue by rodspigolon** [luizpicolo/sigoe#108]
Nem sempre, porem na maioria das vezes ao salvar uma nova ocorrência aparece uma msg de erro(chrome e opera) ou uma tela em branco (mozilla) e não redireciona para nenhuma pagina. Porem a ocorrência fica salva normalmente.

**Comment by luizpicolo** [comment]
Realmente este é um bug que ocorreu na atualização feita ontem. Acredito que seja algo relacionado ao envio de e-mail.

**Comment by luizpicolo** [comment]
@rodspigolon correção realizada. Todas as instâncias do SIGOE foram atualizadas.
